version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "local-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pqv3et85ubsr"
s3_prefix = "local-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
